  <div class="container">

    <div class="page-header">   
      <div class="row">
        <div class="offset2 span10">
          <h1>{__ t='Districts'}</h1>   
        </div>
      </div>
    </div>

    <div class="row">
      
      <div class="span2">       
        <img src="{url::base()}assets/img/logo.png">    
      </div>
      <div class="span6">               
        <div class="white-panel padding20">
            {__ t='<p>Not sure which <em>arrondissement</em> you\'re in? This list of correspondence is here to help!</p>'}
            <table>
            <tbody>
            <tr>
            <td>Quartier</td>
            <td>Arrondissement</td>
            </tr>
            <tr>
            <td>AEROPORT</td>
            <td>DOUALA2</td>
            </tr>
            <tr>
            <td>AKWA</td>
            <td>DOUALA1</td>
            </tr>
            <tr>
            <td>ATELIERS CAMRAIL</td>
            <td>DOUALA3</td>
            </tr>
            <tr>
            <td>BABYLONE</td>
            <td>DOUALA2</td>
            </tr>
            <tr>
            <td>BALI</td>
            <td>DOUALA1</td>
            </tr>
            <tr>
            <td>BANGUE</td>
            <td>DOUALA5</td>
            </tr>
            <tr>
            <td>BASSA</td>
            <td>DOUALA3</td>
            </tr>
            <tr>
            <td>BEEDI</td>
            <td>DOUALA5</td>
            </tr>
            <tr>
            <td>BEPANDA</td>
            <td>DOUALA5</td>
            </tr>
            <tr>
            <td>BEPELE</td>
            <td>DOUALA4</td>
            </tr>
            <tr>
            <td>BESSEKE</td>
            <td>DOUALA4</td>
            </tr>
            <tr>
            <td>BESSENGUE</td>
            <td>DOUALA1</td>
            </tr>
            <tr>
            <td>BILINGUE</td>
            <td>DOUALA4</td>
            </tr>
            <tr>
            <td>BOBONGO</td>
            <td>DOUALA3</td>
            </tr>
            <tr>
            <td>BODJONGO</td>
            <td>DOUALA4</td>
            </tr>
            <tr>
            <td>BOIS DES SINGES</td>
            <td>DOUALA2</td>
            </tr>
            <tr>
            <td>BOKO</td>
            <td>DOUALA3</td>
            </tr>
            <tr>
            <td>BONADIBONG</td>
            <td>DOUALA1</td>
            </tr>
            <tr>
            <td>BONADOUMA</td>
            <td>DOUALA2</td>
            </tr>
            <tr>
            <td>BONAJINJE</td>
            <td>DOUALA1</td>
            </tr>
            <tr>
            <td>BONAKOUAMOUANG</td>
            <td>DOUALA1</td>
            </tr>
            <tr>
            <td>BONAMATOUMBE</td>
            <td>DOUALA4</td>
            </tr>
            <tr>
            <td>BONAMBAPE</td>
            <td>DOUALA4</td>
            </tr>
            <tr>
            <td>BONAMINKANO</td>
            <td>DOUALA4</td>
            </tr>
            <tr>
            <td>BONAMOUANG</td>
            <td>DOUALA1</td>
            </tr>
            <tr>
            <td>BONAMOUSSADI</td>
            <td>DOUALA5</td>
            </tr>
            <tr>
            <td>BONANE</td>
            <td>DOUALA5</td>
            </tr>
            <tr>
            <td>BONANJO</td>
            <td>DOUALA1</td>
            </tr>
            <tr>
            <td>BONANLOKA</td>
            <td>DOUALA3</td>
            </tr>
            <tr>
            <td>BONANTONE</td>
            <td>DOUALA1</td>
            </tr>
            <tr>
            <td>BONAPRISO</td>
            <td>DOUALA1</td>
            </tr>
            <tr>
            <td>BONASSAMA</td>
            <td>DOUALA4</td>
            </tr>
            <tr>
            <td>BONATEKI</td>
            <td>DOUALA1</td>
            </tr>
            <tr>
            <td>BONEBONG</td>
            <td>DOUALA1</td>
            </tr>
            <tr>
            <td>BONELEKE</td>
            <td>DOUALA1</td>
            </tr>
            <tr>
            <td>BONELEKE</td>
            <td>DOUALA1</td>
            </tr>
            <tr>
            <td>BONENDALE</td>
            <td>DOUALA4</td>
            </tr>
            <tr>
            <td>BONEWONDA</td>
            <td>DOUALA5</td>
            </tr>
            <tr>
            <td>BRAZZAVILLE</td>
            <td>DOUALA3</td>
            </tr>
            <tr>
            <td>C C C</td>
            <td>DOUALA3</td>
            </tr>
            <tr>
            <td>CAMP YABASSI</td>
            <td>DOUALA2</td>
            </tr>
            <tr>
            <td>CCC</td>
            <td>DOUALA3</td>
            </tr>
            <tr>
            <td>CITE BERGE</td>
            <td>DOUALA3</td>
            </tr>
            <tr>
            <td>CITE CICA</td>
            <td>DOUALA5</td>
            </tr>
            <tr>
            <td>CITE DES PALMIERS</td>
            <td>DOUALA5</td>
            </tr>
            <tr>
            <td>CITE-SIC</td>
            <td>DOUALA5</td>
            </tr>
            <tr>
            <td>CONGO</td>
            <td>DOUALA2</td>
            </tr>
            <tr>
            <td>DIBOM</td>
            <td>DOUALA3</td>
            </tr>
            <tr>
            <td>GENDARMERIE MBOPI</td>
            <td>DOUALA3</td>
            </tr>
            <tr>
            <td>GENIE MILITAIRE</td>
            <td>DOUALA3</td>
            </tr>
            <tr>
            <td>GRAND HANGAR</td>
            <td>DOUALA4</td>
            </tr>
            <tr>
            <td>GRAND MOULIN</td>
            <td>DOUALA1</td>
            </tr>
            <tr>
            <td>GRDE TRAME MBANGA JAP</td>
            <td>DOUALA3</td>
            </tr>
            <tr>
            <td>JAPOMA</td>
            <td>DOUALA3</td>
            </tr>
            <tr>
            <td>KAMBO</td>
            <td>DOUALA3</td>
            </tr>
            <tr>
            <td>KM 5</td>
            <td>DOUALA2</td>
            </tr>
            <tr>
            <td>KOTTONGOMA</td>
            <td>DOUALA5</td>
            </tr>
            <tr>
            <td>LOBE</td>
            <td>DOUALA4</td>
            </tr>
            <tr>
            <td>LOGBABA</td>
            <td>DOUALA3</td>
            </tr>
            <tr>
            <td>LOGBESSOU</td>
            <td>DOUALA5</td>
            </tr>
            <tr>
            <td>LOGPOM</td>
            <td>DOUALA5</td>
            </tr>
            <tr>
            <td>MABANDA</td>
            <td>DOUALA4</td>
            </tr>
            <tr>
            <td>MADAGASCAR</td>
            <td>DOUALA3</td>
            </tr>
            <tr>
            <td>MAKEANGANGUE</td>
            <td>DOUALA2</td>
            </tr>
            <tr>
            <td>MAKEPE</td>
            <td>DOUALA5</td>
            </tr>
            <tr>
            <td>MALANGUE</td>
            <td>DOUALA5</td>
            </tr>
            <tr>
            <td>MBANGA&nbsp;</td>
            <td>DOUALA3</td>
            </tr>
            <tr>
            <td>MBONANGANG</td>
            <td>DOUALA5</td>
            </tr>
            <tr>
            <td>NDOBO</td>
            <td>DOUALA4</td>
            </tr>
            <tr>
            <td>NDOGBATI</td>
            <td>DOUALA5</td>
            </tr>
            <tr>
            <td>NDOGMBE</td>
            <td>DOUALA3</td>
            </tr>
            <tr>
            <td>NDOGPASSI</td>
            <td>DOUALA3</td>
            </tr>
            <tr>
            <td>NDOGSIMBI</td>
            <td>DOUALA3</td>
            </tr>
            <tr>
            <td>NDOKOTI</td>
            <td>DOUALA3</td>
            </tr>
            <tr>
            <td>NEW BELL</td>
            <td>DOUALA2</td>
            </tr>
            <tr>
            <td>NEW-DEIDO</td>
            <td>DOUALA1</td>
            </tr>
            <tr>
            <td>NEWTOWN</td>
            <td>DOUALA2</td>
            </tr>
            <tr>
            <td>NGODI</td>
            <td>DOUALA1</td>
            </tr>
            <tr>
            <td>NGWELE</td>
            <td>DOUALA4</td>
            </tr>
            <tr>
            <td>NKOLB</td>
            <td>DOUALA3</td>
            </tr>
            <tr>
            <td>NKOLMINTA</td>
            <td>DOUALA3</td>
            </tr>
            <tr>
            <td>NKOLOLOUN</td>
            <td>DOUALA2</td>
            </tr>
            <tr>
            <td>NKOMBA</td>
            <td>DOUALA4</td>
            </tr>
            <tr>
            <td>NKONDO</td>
            <td>DOUALA1</td>
            </tr>
            <tr>
            <td>NKONGMONDO</td>
            <td>DOUALA1</td>
            </tr>
            <tr>
            <td>NYALA BASSA</td>
            <td>DOUALA3</td>
            </tr>
            <tr>
            <td>NYLON</td>
            <td>DOUALA3</td>
            </tr>
            <tr>
            <td>OKOUMASSI</td>
            <td>DOUALA1</td>
            </tr>
            <tr>
            <td>OYACK</td>
            <td>DOUALA3</td>
            </tr>
            <tr>
            <td>PINDO</td>
            <td>DOUALA5</td>
            </tr>
            <tr>
            <td>SIC&nbsp; CACAO</td>
            <td>DOUALA5</td>
            </tr>
            <tr>
            <td>SODIKO</td>
            <td>DOUALA4</td>
            </tr>
            <tr>
            <td>SODIKOMBO</td>
            <td>DOUALA5</td>
            </tr>
            <tr>
            <td>SONGBIKAKO</td>
            <td>DOUALA3</td>
            </tr>
            <tr>
            <td>TERGAL</td>
            <td>DOUALA3</td>
            </tr>
            <tr>
            <td>VILLAGE</td>
            <td>DOUALA2</td>
            </tr>
            <tr>
            <td>YIKENDOGBONG</td>
            <td>DOUALA5</td>
            </tr>
            <tr>
            <td>YOUPWE</td>
            <td>DOUALA2</td>
            </tr>
            </tbody>
            </table>
        </div>    
      </div>

    </div>    

  </div>